parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\IAmAlive\Infrastructure\Controller\IAmAliveController:
    arguments:
      $buildNumber: '%env(BUILD_NUMBER)%'
      $commitHash: '%env(COMMIT_HASH)%'
    tags: [ 'controller.service_arguments' ]