IAmAlive:
    resource:
        path: ../src/IAmAlive/Infrastructure/Controller/
        namespace: App\IAmAlive\Infrastructure\Controller
    type: attribute

Auth:
    resource:
        path: ../src/Auth/Infrastructure/Controller/
        namespace: App\Auth\Infrastructure\Controller
    type: attribute
