parameters:

imports:
  - { resource: services/ }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\IAmAlive\Infrastructure\Controller\IAmAliveController:
    tags: [ 'controller.service_arguments' ]
