parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: false

  App\Auth\Domain\Factory\RoleFactoryInterface: '@App\Auth\Application\Factory\RoleFactory'
  App\Auth\Domain\Factory\UserFactoryInterface: '@App\Auth\Application\Factory\UserFactory'
  App\Auth\Domain\Repository\UserRepositoryInterface: '@App\Auth\Infrastructure\Repository\UserRepository'
  App\Auth\Domain\Repository\RoleRepositoryInterface: '@App\Auth\Infrastructure\Repository\RoleRepository'

  App\Auth\Application\EventListener\PostControllerDataListener:
    tags: [ 'kernel.event_subscriber' ]

  App\Auth\Application\Service\SlugService:

  App\Auth\Application\Factory\RoleFactory:

  App\Auth\Application\Factory\UserFactory:

  App\Auth\Infrastructure\Controller\:
    resource: "../src/Auth/Infrastructure/Controller"
    tags: [ 'controller.service_arguments' ]

  App\Auth\Infrastructure\Repository\RoleRepository:
    tags: [ 'doctrine.repository_service' ]

  App\Auth\Infrastructure\Repository\UserRepository:
    tags: [ 'doctrine.repository_service' ]