parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  test.validator: '@validator'

  App\Tests\DataFixtures\:
    resource: '../tests/DataFixtures'
    tags: [ 'doctrine.fixture.orm' ]