parameters:

imports:
  - { resource: services/ }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\IAmAlive\Infrastructure\Controller\IAmAliveController:
    tags: [ 'controller.service_arguments' ]

  App\Auth\Domain\Repository\UserRepositoryInterface: '@App\Auth\Infrastructure\Repository\UserRepository'

  App\Auth\Application\Factory\:
    resource: '../src/Auth/Application/Factory'

  App\Auth\Infrastructure\Repository\:
    resource: '../src/Auth/Infrastructure/Repository/'
    tags: [ 'doctrine.repository_service' ]

  App\Auth\Infrastructure\Controller\UserController\RegisterController:
    arguments:
      $userRepository: '@App\Auth\Infrastructure\Repository\UserRepository'
    tags: [ 'controller.service_arguments' ]