parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $requestValidators: !tagged_iterator 'request.validators'

  App\IAmAlive\Infrastructure\Controller\IAmAliveController:
    tags: [ 'controller.service_arguments' ]

  App\Validator\Application\Manager\RequestValidatorManager:

  App\Validator\Domain\RequestValidators\:
    resource: '../src/Validator/Domain/RequestValidators/'
    tags: [ 'request.validators' ]